# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "auro.lewis@auro.com"
          
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: |
          npm install ./.github/components/version-helper

      - name: Standard Version
        uses: qzb/standard-version-action@v1.0.7

      - name: Commit version changes
        if: github.event_name == 'push'
        run: |
          git push --follow-tags origin $GITHUB_REF
